[[template]]
    src         = "${REMCO_TEMPLATE_DIR}/rundeck-config-storage.properties"
    dst         = "${REMCO_TMP_DIR}/rundeck-config/rundeck-config-storage.properties"
    mode        = "0644"
